# Домашнее задание "Основные математические понятия".

## Уровень 0:


Представим фильмы в виде бинарных векторов (numpy array) используя следующие признаки:

[Комедия, Боевик, Исторический, Бред Питт, Бенедикт Камбербэтч, Квентин Тарантино]

[Игра в имитацию](https://www.kinopoisk.ru/film/635772/)

[Ярость](https://www.kinopoisk.ru/film/740644/)

[12 лет рабства](https://www.kinopoisk.ru/film/606646/)

[Однажды в Голливуде](https://www.kinopoisk.ru/film/1047883/)

```
film_1 = np.array([0,0,0,0,1,0])      # Игра в имитацию

film_2 = np.array([0,1,0,1,0,0])      # Ярость

film_3 = np.array([0,0,1,1,1,0])      # 12 лет рабства

film_4 = np.array([1,0,0,1,0,1])      # Однажды в Голливуде
```



In [4]:
import numpy as np
film_1 = np.array([0,0,0,0,1,0])      # Игра в имитацию
film_2 = np.array([0,1,0,1,0,0])      # Ярость
film_3 = np.array([0,0,1,1,1,0])      # 12 лет рабства
film_4 = np.array([1,0,0,1,0,1])      # Однажды в Голливуде


### Задание 1

Найти угол между векторами-фильмами "Ярость" и "12 лет рабства". Результатом будет являться косинусная мера, которую можно использовать для определения похожести векторов.

In [5]:
#ищем угол между векторами
# скалярное произведение делим на произведение евклидовых норм, далее ищем аркосинус и переводим в градусы
np.rad2deg( np.arccos(np.dot(film_2,film_3)/(np.linalg.norm(film_2) * np.linalg.norm(film_3) )))

65.90515744788931

## Уровень 1:

### Задание 2

Вычислить с помощью Python значение первой производной для функции $8x(x+3)^2$ в точке $x=1$


In [6]:
import sympy as sym

In [7]:
x = sym.Symbol('x')

In [8]:
 8*x*(x+3)**2

8*x*(x + 3)**2

In [10]:
# получаем аналитическую производную
res = sym.diff( 8*x*(x+3)**2,x)
res

8*x*(2*x + 6) + 8*(x + 3)**2

In [11]:
res.subs(x,1)

192

### Задание 3


Объединить векторы фильмов в матрицу, где каждый вектор является строкой матрицы. Умножьте вектор [1,2,3,4] на полученную матрицу

In [14]:
film = np.array([film_1,film_2,film_3,film_4])
v = np.array([1,2,3,4])

In [15]:
film

array([[0, 0, 0, 0, 1, 0],
       [0, 1, 0, 1, 0, 0],
       [0, 0, 1, 1, 1, 0],
       [1, 0, 0, 1, 0, 1]])

In [16]:
v

array([1, 2, 3, 4])

In [18]:
itog = np.dot(v,film)
itog

array([4, 2, 3, 9, 4, 4])